### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by cjessett** [DImOrf/Jamming-Review#4]
(Meets Expectations) Overall, nice work.

Remember to store sensitive variables that you don't want to share in the environment via `process.env`. Also, remember that chained promises should be indented the same amount and that we reserve `let` for variables that are reassigned.

Otherwise, your code is clean and easy to follow, nice job.

**Comment by DImOrf** [comment]
Thank you very much for the comments. 
I will make the corrections on my free time.
Enjoyed a lot making this project!
